development:
  data:
    adapter: mysql2
    encoding: utf8mb4
    database: ar_without_rails_playground
    pool: 5
    username: root
    password: <%= ENV['MYSQL_PASSWORD'] %>
    host: <%= ENV['MYSQL_HOST'] %>

  datacenter:
    adapter: mysql2
    encoding: utf8mb4
    database: ar_without_rails_aggregation
    pool: 5
    username: root
    password: <%= ENV['DATACENTER_MYSQL_PASSWORD'] %>
    host: <%= ENV['DATACENTER_MYSQL_HOST'] %>
